export const LOADING = {
  SET_LOADING: 'SET_LOADING',
  RESET_LOADING: 'RESET_LOADING'
};

export const ROUTES = {
  SET_ROUTES: 'SET_ROUTES'
};

export const CUSTOMER = {
  SET_SELECTED_ROW: 'SET_SELECTED_ROW'
};

export const INVOICE = {
  UPDATE_CUSTOMER_DETAILS: 'UPDATE_CUSTOMER_DETAILS',
  UPDATE_PRODUCTS: 'UPDATE_PRODUCTS',
  UPDATE_TAX_DETAILS: 'UPDATE_TAX_DETAILS',
  SET_FORM: 'SET_FORM'
};
