export const LOADING = {
  SET_LOADING: 'SET_LOADING',
  RESET_LOADING: 'RESET_LOADING'
};

export const ROUTES = {
  SET_ROUTES: 'SET_ROUTES'
};

export const CUSTOMER = {
  SET_SELECTED_ROW: 'SET_SELECTED_ROW'
};
