export const LOADING = {
  SET_LOADING: 'SET_LOADING',
  RESET_LOADING: 'RESET_LOADING'
};

export const AUDIO_TO_TEXT = {
  UPLOAD_AND_CONVERT: 'UPLOAD_AND_CONVERT'
};

export const FACE_RECOGNITION = {
  PREDICT_GENDER: 'PREDICT_GENDER'
};

export const PRINT = {
  CONTENT: 'CONTENT'
};
